<template>
    <div id="app">
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
        <div class="wave">
            <svg viewBox="0 0 500 550" preserveAspectRatio="none">
                <path
                    d="M-10.44,152.45 C172.40,50.81 316.87,206.73 502.54,116.94 L500.00,0.00 L0.00,0.00 Z"
                />
            </svg>
        </div>
        <Header />
        <Content />
        <Footer />
    </div>
</template>

<script>
import Header from "./components/template/Header";
import Content from "./components/template/Content";
import Footer from "./components/template/Footer";

export default {
    name: "App",
    components: { Header, Content, Footer }
};
</script>

<style>
body {
    margin: 0;
}
* {
    box-sizing: border-box;
}
#app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    background-color: #e5f9ff;

    color: #333;
    height: 100vh;
    display: grid;
    grid-template: "header" "content" "footer";
    grid-template-rows: 80px 1fr 22px;
    grid-template-columns: 1fr;
}
.wave {
    position: fixed;
    width: 100%;
    height: 150%;
    top: 0px;
}
.wave svg {
    height: 100%;
    width: 100%;
}
.wave path {
    stroke: #1a6eff4f;
    fill: #08f3;
}
</style>
